services:
  web:
    image: ghcr.io/cookbookio/awsome-recipe-cookbook:latest
    build:
      context: ..
      dockerfile: src/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
